name: Drivetec API CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Java (JDK 17 in your case)
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Cache Maven dependencies to speed up builds
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Install dependencies and run tests with Maven
    - name: Build and Test with Maven
      run: mvn test -Dkarate.options="--tags @drivetec"

    # Step 5: Upload test results to GitHub Actions
    - name: Upload Karate Test Report
      uses: actions/upload-artifact@v3
      with:
        name: karate-test-report
        path: target/cucumber-html-reports
